name: Build Paper PDF

on:
  workflow_dispatch:
  push:
    branches:
      - paper
  pull_request:
    branches:
      - paper

jobs:
  build-paper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile Paper PDF
        uses: docker://openbases/builder-pdf

      - name: Upload Generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper.pdf
